[package]
name = "cf-equipment"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
ron = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
cf-atmos = { path = "../cf-atmos" }
cf-disease = { path = "../cf-disease" }
cf-mental-health = { path = "../cf-mental-health" }

