[package]
name = "cf-flask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
cf-material = { path = "../cf-material" }
cf-terrain = { path = "../cf-terrain" }

[dev-dependencies]
