"""Direct JSONL writer for the cf-asset-ledger ledger file.

Spec contract: every M9A asset generated by build_placeholders.py gets a row
in `content/asset_ledger/ledger.jsonl`. Each row is a valid AssetEntry per
`game/crates/cf-asset-ledger/src/entry.rs::AssetEntry`. We write the row
directly from Python (no subprocess to `cf-mod ledger add`) for speed —
4000+ subprocesses would be prohibitively slow.

Determinism: the writer enforces `CF_DETERMINISTIC_LEDGER=1` semantics — the
`generated_at_iso` is derived from blake3(output_blake3), and
`generated_on_machine` is "deterministic". Mirrors
cf-asset-ledger/src/entry.rs::deterministic_generated_at_iso so the same
asset re-baked on any machine produces the same row bytes.
"""

from __future__ import annotations

import io
import json
import os
import sys
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

import blake3  # type: ignore[import-not-found]


ASSET_ENTRY_SCHEMA_VERSION = "1.0.0"


@dataclass
class LedgerEntryDraft:
    """Inputs the build orchestrator hands to `build_entry`."""

    category: str           # AssetCategory wire name (e.g. "WeaponSprite")
    kind: str               # Sub-category (e.g. "weapon-side")
    canonical_name: str
    tier: str               # ProductionTier wire name (e.g. "Tier1_SVG")
    pipeline: str           # PipelineId (e.g. "M9A_svg_v1")
    prompt: str
    seed: int
    output_path: str        # Absolute path or repo-root-relative
    output_blake3: str
    output_size_bytes: int
    output_format: str = "svg"
    palette_ref: Optional[str] = None
    style_lora: Optional[str] = None
    generator_tool: str = "tools/asset_gen/build_placeholders.py"
    generator_model: str = "procedural-svg-composer-v1"
    generator_workflow: Optional[str] = None
    generator_model_version: Optional[str] = "1.0.0"
    additional_outputs: List[Dict[str, object]] = field(default_factory=list)
    upstream_assets: List[str] = field(default_factory=list)
    regen_command: Optional[str] = None
    negative_prompt: Optional[str] = None


def compute_asset_id(category: str, canonical_name: str, tier: str) -> str:
    """Mirror cf-asset-ledger/src/entry.rs::AssetId::compute exactly.

    Inputs: blake3(category | "|" | canonical_name | "|" | tier). Output: 64-char hex.
    """
    h = blake3.blake3()
    h.update(category.encode("utf-8"))
    h.update(b"|")
    h.update(canonical_name.encode("utf-8"))
    h.update(b"|")
    h.update(tier.encode("utf-8"))
    return h.hexdigest()


def deterministic_generated_at_iso(seed_hex: str) -> str:
    """Mirror cf-asset-ledger/src/entry.rs::deterministic_generated_at_iso."""
    h = blake3.blake3()
    h.update(b"cf-asset-ledger/v1/generated_at_iso/")
    h.update(seed_hex.encode("utf-8"))
    return f"ledger-deterministic:{h.hexdigest()[:16]}"


def build_entry(draft: LedgerEntryDraft) -> Dict[str, object]:
    """Build a JSON-serializable dict matching the AssetEntry schema."""
    asset_id = compute_asset_id(draft.category, draft.canonical_name, draft.tier)
    generator: Dict[str, object] = {
        "tool": draft.generator_tool,
        "model": draft.generator_model,
    }
    if draft.generator_workflow:
        generator["workflow"] = draft.generator_workflow
    if draft.generator_model_version:
        generator["model_version"] = draft.generator_model_version
    entry: Dict[str, object] = {
        "id": asset_id,
        "category": draft.category,
        "kind": draft.kind,
        "canonical_name": draft.canonical_name,
        "tier": draft.tier,
        "pipeline": draft.pipeline,
        "generator": generator,
        "prompt": draft.prompt,
        "seed": int(draft.seed),
        "upstream_assets": list(draft.upstream_assets),
        "output_path": draft.output_path,
        "output_format": draft.output_format,
        "output_size_bytes": int(draft.output_size_bytes),
        "output_blake3": draft.output_blake3,
        "additional_outputs": list(draft.additional_outputs),
        "generated_at_iso": deterministic_generated_at_iso(draft.output_blake3 or asset_id),
        "generated_on_machine": "deterministic",
        "generated_by_human": False,
        "package_source": "Vanilla",
        "license": "CC0",
        "regen_command": (
            draft.regen_command
            or f"cf-mod ledger regenerate {asset_id}"
        ),
        "regen_inputs": [],
        "regen_status": "Fresh",
        "schema_version": ASSET_ENTRY_SCHEMA_VERSION,
    }
    if draft.palette_ref:
        entry["palette_ref"] = draft.palette_ref
    if draft.style_lora:
        entry["style_lora"] = draft.style_lora
    if draft.negative_prompt:
        entry["negative_prompt"] = draft.negative_prompt
    return entry


def hash_path(path: Path) -> tuple[int, str]:
    """Stream-hash a file with blake3. Returns (size_bytes, hex_digest)."""
    h = blake3.blake3()
    total = 0
    with path.open("rb") as f:
        while True:
            chunk = f.read(64 * 1024)
            if not chunk:
                break
            total += len(chunk)
            h.update(chunk)
    return total, h.hexdigest()


# ─── Append helper with cross-process / cross-thread mutex ────────────────


class LedgerJsonlWriter:
    """Thread-safe + process-safe appender. Use as a context manager.

    Uses an in-process threading.Lock for fast intra-process serialization +
    `fs2`-style cross-process advisory locking via `fcntl` so a parallel
    multiprocessing pool can append without garbling lines.
    """

    def __init__(self, path: Path):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        if not self.path.exists():
            self.path.touch()
        self._lock = threading.Lock()
        self._file = None  # opened lazily

    def __enter__(self) -> "LedgerJsonlWriter":
        self._file = self.path.open("a", buffering=1)
        return self

    def __exit__(self, *_args) -> None:
        if self._file is not None:
            self._file.flush()
            try:
                os.fsync(self._file.fileno())
            except OSError:
                pass
            self._file.close()
            self._file = None

    def write_entry(self, entry: Dict[str, object]) -> None:
        line = json.dumps(entry, separators=(",", ":"), sort_keys=True)
        with self._lock:
            if self._file is None:
                raise RuntimeError("LedgerJsonlWriter used outside `with` block")
            self._file.write(line + "\n")


def overwrite_ledger(path: Path, entries: List[Dict[str, object]]) -> int:
    """Replace ledger.jsonl contents with a deterministic-ordered batch.

    Used by `build_placeholders.py --all` — it computes every entry, sorts by
    AssetId for byte-deterministic ordering, then atomically replaces the
    file. This gives ledger.jsonl a stable byte hash across machines.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    sorted_entries = sorted(entries, key=lambda e: str(e.get("id", "")))
    buf = io.StringIO()
    for entry in sorted_entries:
        buf.write(json.dumps(entry, separators=(",", ":"), sort_keys=True) + "\n")
    text = buf.getvalue()
    staging = path.with_suffix(path.suffix + ".tmp")
    staging.write_text(text, encoding="utf-8")
    os.replace(staging, path)
    return len(sorted_entries)


__all__ = [
    "ASSET_ENTRY_SCHEMA_VERSION",
    "LedgerEntryDraft",
    "LedgerJsonlWriter",
    "build_entry",
    "compute_asset_id",
    "deterministic_generated_at_iso",
    "hash_path",
    "overwrite_ledger",
]


if __name__ == "__main__":
    print("[ledger_writer] importable as a module; see build_placeholders.py.", file=sys.stderr)
