//! Schemas for the cf-control envelope. Output JSON Schema files live under
//! `crates/cf-control/schemas/v1/` and are regenerated by `cargo run -p cf-control --example
//! dump_schemas`. The crate test verifies the static files match the `schemars` output for
//! the current types.

use std::collections::BTreeMap;

use schemars::{schema_for, JsonSchema};
use serde::{Deserialize, Serialize};

/// Protocol schema version. Bumped from 1→2 at BP3 when M5 added
/// `act.player.crouch/climb/jet/eject` plus `act.chassis.repair/salvage/clear_jam`
/// plus `act.input.focus`. Clients sending `schema_version: 1` still work because
/// all new methods are additive (no field renames or type changes on v1 methods).
/// The dispatcher rejects `schema_version > SCHEMA_VERSION` with `-32602`.
pub const SCHEMA_VERSION: u32 = 2;

/// Minimum schema version accepted. v1 clients are still compatible because
/// no v1 method shapes changed — only new methods were added.
pub const SCHEMA_VERSION_MIN: u32 = 1;

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ScenarioLoadParams {
    pub schema_version: u32,
    pub scenario: String,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub seed: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct CommandAck {
    pub schema_version: u32,
    pub status: String,
    pub effective_tick: u64,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub reason: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct StepParams {
    pub schema_version: u32,
    pub ticks: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct RunForTicksParams {
    pub schema_version: u32,
    pub ticks: u64,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub write_run_bundle: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveOnceParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub filter: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveSubscribeParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub hz: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub filter: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerMoveParams {
    pub schema_version: u32,
    /// Move axis in [-1.0, +1.0]. Negative = left, positive = right.
    pub x: f32,
    /// Reserved for vertical input (ladders / climbing). Ignored in M1.
    #[serde(default)]
    pub y: f32,
}

/// `act.player.jump` — edge-triggered jump request.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerJumpParams {
    pub schema_version: u32,
}

/// `act.player.aim` — set the player's aim vector (will be normalized).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerAimParams {
    pub schema_version: u32,
    pub x: f32,
    pub y: f32,
}

/// `act.player.fire` — edge-triggered fire request.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerFireParams {
    pub schema_version: u32,
    /// `true` (default) = press fire this tick; `false` = explicit release for future
    /// hold-to-fire weapons. M1's rifle is single-press; release is a no-op.
    #[serde(default = "default_true")]
    pub pressed: bool,
    /// `cfctl.act.player.fire` ammo-kind" — optional snake_case ammo
    /// kind selector. Accepted values: `regular`, `tracer`, `high_explosive`,
    /// `pellet`, `heat`, `apfsds`. `None` = use the weapon's default
    /// round (existing M6 behavior). Unknown values reject at the
    /// dispatch boundary with `unknown_ammo_kind`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ammo_kind: Option<String>,
}

/// `act.player.reload` — edge-triggered reload request.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerReloadParams {
    pub schema_version: u32,
}

/// `act.player.select_item` — set the active inventory slot.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerSelectItemParams {
    pub schema_version: u32,
    pub slot: u32,
}

/// `act.player.reset` — return the player to their spawn with full HP / ammo.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerResetParams {
    pub schema_version: u32,
}

/// `act.player.dig` — M1.5 soft-breach dig request. `target` picks an explicit
/// breach id; `None` means dig the nearest in-range strip.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerDigParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub target: Option<String>,
}

/// `act.player.dig_trench_segment` — request a trench carve at the
/// player's current tile. `variant` is one of the 6 declared
/// cross-section variants (`shallow_scrape` / `standard` / `deep` /
/// `communication` / `fire_step` / `parapet_raised`). `tool_id` selects
/// the dig tool (`entrenching_tool` T0 baseline, or
/// `pickaxe_dig_t1` / `pickaxe_dig_t2` / `pickaxe_dig_t3` from the
/// M30B-tier ladder). `substrate_hardness` (`[0.0, 1.0]`) gates the
/// `deep` variant per VAL-M9B-DIG-003 — `>= 0.5` falls back to
/// `shallow_scrape` with a `trench.segment_variant_downgraded` warning
/// event (or rejects when `strict=true`).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerDigTrenchSegmentParams {
    pub schema_version: u32,
    pub variant: String,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tool_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub substrate_hardness: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub strict: Option<bool>,
}

/// `act.player.place_trench_module` — place an embedded trench module
/// on a built segment. `module_id` is one of the 6 declared modules
/// (`duckboard` / `fire_step` / `breastwork` / `drainage_sump` /
/// `revetment` / `corner_traverse`). `segment_id` identifies the
/// target trench segment instance.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerPlaceTrenchModuleParams {
    pub schema_version: u32,
    pub module_id: String,
    pub segment_id: u64,
}

/// `act.player.drop_trench_template` — instantiate an authored trench
/// template at the supplied tile origin. `id` resolves to
/// `content/trench_templates/<id>.trench.ron`; the cfctl handler
/// hashes the template (`template_sha256`) + counts placed segments
/// (`segment_count`) into the `trench.template_dropped` event.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerDropTrenchTemplateParams {
    pub schema_version: u32,
    pub id: String,
    pub origin: (i32, i32),
}

/// `act.player.repair_trench_module` — repair a damaged trench module.
/// Consumes the declared per-module resources (wood / iron / sandbag)
/// and emits `trench.module_repaired`.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerRepairTrenchModuleParams {
    pub schema_version: u32,
    pub module_id: String,
    pub segment_id: u64,
}

/// the actor's current trench cover state. Returns
/// `{ cover_state: "Exposed" | "Partial" | "Full" }`. `actor_id=None`
/// resolves to the player.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveActorCoverStateParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub actor_id: Option<u64>,
}

/// read the trench segment at the supplied tile, or `null` for open
/// ground.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveTrenchSegmentAtPosParams {
    pub schema_version: u32,
    pub x: i32,
    pub y: i32,
}

/// tether / anchor / rope-grapple at world-space `(x, y)`. The engine samples
/// the material at the target and emits `terrain.anchor_material_result`:
/// - `anchorable=true` (dirt, concrete, anchor) → `result="accepted"`
/// - `anchorable=false` (metal_nohook, hazard, loose_fill) → `result="refused"`
///   with `reason="material_<name>"`
///
/// `tool_id` is optional ("grapple" / "tether_gun" / "rope_anchor"); defaults
/// to `"anchor_tool"`. Spec ref: `specs/active/M3.md` § Re-opened gaps, MAT-T-06.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerAnchorParams {
    pub schema_version: u32,
    pub x: f64,
    pub y: f64,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tool_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerCrouchParams {
    pub schema_version: u32,
    pub active: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerClimbParams {
    pub schema_version: u32,
    pub active: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerJetParams {
    pub schema_version: u32,
    pub active: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerEjectParams {
    pub schema_version: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerQuickActionSlotParams {
    pub schema_version: u32,
    /// 1-8 inclusive (the player-facing numbering); engine subtracts 1 internally.
    pub slot: u8,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerQuickActionToggleParams {
    pub schema_version: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerQuickActionRadialParams {
    pub schema_version: u32,
    pub active: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerQuickActionSliceParams {
    pub schema_version: u32,
    pub slice: u8,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerWeaponCycleParams {
    pub schema_version: u32,
    /// -1 or +1.
    pub direction: i8,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActChassisRepairParams {
    pub schema_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub zone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub module_id: Option<String>,
    #[serde(default = "default_repair_reason")]
    pub reason: String,
}

fn default_repair_reason() -> String {
    "field_kit".to_string()
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActChassisSalvageParams {
    pub schema_version: u32,
    #[serde(default = "default_salvage_reason")]
    pub reason: String,
}

fn default_salvage_reason() -> String {
    "manual".to_string()
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActChassisClearJamParams {
    pub schema_version: u32,
}

/// (CCCP `AHuman.cpp:1779`). While `active=true` the sim builds
/// `ActorState::sharp_aim_progress` toward 1.0 each tick as long as the
/// actor is STABLE, grounded, slow, and equipped; invalidations snap it back
/// to zero.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerSharpAimParams {
    pub schema_version: u32,
    pub active: bool,
}

/// AI hints + tracer/particle metadata) for a preset id.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct InspectEquipmentParams {
    pub schema_version: u32,
    pub preset_id: String,
}

/// player by default, or for `actor_id` when supplied.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveActorParams {
    pub schema_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<u64>,
}

/// `actor` events for the target. `target` is `"player"` for the controllable
/// actor or an actor id rendered as a string. Empty target defaults to player.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct InspectActorParams {
    pub schema_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
}

/// joints + 5 sockets) plus per-zone integrity, per-module state, pilot state
/// and the eject window for an actor's chassis. `target` is `"player"` (or
/// empty) for the controllable actor, or a stringified actor id.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct InspectChassisParams {
    pub schema_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
}

/// transfers control to a different friendly actor and updates the brain flag.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerBrainHopParams {
    pub schema_version: u32,
    pub target_actor_id: u64,
}

/// ability slots.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerActivateAbilityParams {
    pub schema_version: u32,
    pub ability: String,
}

/// first-person cockpit camera anchors.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActInputCameraAnchorParams {
    pub schema_version: u32,
    pub mode: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerSetDroneModeParams {
    pub schema_version: u32,
    pub mode: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerAttachModifierParams {
    pub schema_version: u32,
    pub modifier: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerDetachModifierParams {
    pub schema_version: u32,
    pub modifier: String,
}

/// boarding transition into a chassis actor.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerBoardParams {
    pub schema_version: u32,
    pub chassis_actor_id: u64,
}

/// disembarking transition.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerDisembarkParams {
    pub schema_version: u32,
}

/// projection (per-zone HP for the chassis side of the dual layer).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveChassisSilhouetteParams {
    pub schema_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<u64>,
}

/// `MissionState` projection. No params required.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveMissionParams {
    pub schema_version: u32,
}

/// `actor_id`. Includes guard state + perception summary + current target +
/// reason vocabulary.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveAiParams {
    pub schema_version: u32,
    pub actor_id: u64,
}

/// (sight cone + hearing radius + stealth meter + last footstep loudness
/// band + last occlusion factor). `actor_id=None` resolves to the player.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObservePerceptionParams {
    pub schema_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<u64>,
}

/// `MissionState` + objectives[] + commander stub. No params required.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct InspectMissionParams {
    pub schema_version: u32,
}

/// state + memory grid contents + last 30 ai events.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct InspectAiParams {
    pub schema_version: u32,
    pub actor_id: u64,
}

/// stub at M1; flips to a real mission abort path at M1.5.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerAbortParams {
    pub schema_version: u32,
}

/// timer accounting (tutorial-modal pause path). Idempotent: invoking
/// twice in a row only emits one `mission.objective_paused` event.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActMissionPauseParams {
    #[serde(default)]
    pub schema_version: u32,
}

/// Idempotent: only emits `mission.objective_resumed` when actually paused.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActMissionResumeParams {
    #[serde(default)]
    pub schema_version: u32,
}

/// that an overlay (settings panel, debrief prompt, future pause/menu) has
/// captured input. `captured=true` raises the CONTROLS CAPTURED HUD badge
/// and rejects subsequent `act.player.*` dispatches; `captured=false`
/// releases. `capturer` carries a short human-readable label.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActInputCaptureControlsParams {
    pub schema_version: u32,
    pub captured: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capturer: Option<String>,
}

/// material overlay mode. `mode = None` cycles through
/// off → integrity → pathability → mobility → hazard → build_repair → off.
/// `mode = Some("...")` sets explicitly. Emits `ux.overlay_mode_changed`.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActToggleMaterialOverlayParams {
    #[serde(default)]
    pub schema_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
}

/// plus dirty rect, last_modified_tick, and chunk_checksum for the
/// requested chunk coord.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct InspectTerrainChunkParams {
    pub schema_version: u32,
    pub x: i32,
    pub y: i32,
}

/// resolved either by canonical material id OR by snake-case material name
/// (e.g. `iron`, `steel`). Exactly one of `id` / `name` must be supplied;
/// providing both is OK and `id` wins. Used by the cfctl `inspect.material`
/// command (M15C spec § "Per-material properties accessible via cfctl"):
/// `cfctl inspect.material iron` → resolves the name to id 68 then dumps
/// the full MaterialDef.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct InspectMaterialParams {
    pub schema_version: u32,
    #[serde(default)]
    pub id: Option<u16>,
    #[serde(default)]
    pub name: Option<String>,
}

/// returns the MaterialInfo at world-space coordinates with the nine
/// affordance flags (actor_passable, projectile_passable, diggable,
/// anchorable, blocks_light, contact_damage, path_cost, produces_debris,
/// produces_sound) plus integrity (from the per-pixel meta grid) plus
/// color_hex (from the material registry). Powers spec § "Material
/// affordance tooltip" and the integrity-overlay reticle.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveTerrainMaterialAtParams {
    pub schema_version: u32,
    pub x: f32,
    pub y: f32,
}

/// command grammar to a squad. Spec § "50+ named squad verbs in a
/// data-driven registry".
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActSquadIssueParams {
    pub schema_version: u32,
    pub squad_id: u64,
    pub verb_id: String,
    #[serde(default)]
    pub args: Vec<serde_json::Value>,
}

/// kind (Wedge / Diamond / Column / Line Abreast / Echelon-Left /
/// Echelon-Right / Single-File / Stack (door) / Defensive Perimeter).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActSquadSetFormationParams {
    pub schema_version: u32,
    pub squad_id: u64,
    pub formation_kind: String,
}

/// (Pointman / Rifleman / Marksman / Heavy / Engineer / Medic /
/// Squad Leader).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActSquadAssignRoleParams {
    pub schema_version: u32,
    pub squad_id: u64,
    pub member_actor_id: u64,
    pub role: String,
}

/// view (verb registry + formation catalog + archetype-BT node counts +
/// per-squad state row). Used by the M25 wheel + Tab overlay + assert
/// the spec's "verb registry enumerates 50+ named squad commands"
/// invariant.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct SrvDumpSquadStateParams {
    pub schema_version: u32,
    #[serde(default)]
    pub squad_id: u64,
}

/// currently-playing cinematic. Per spec § "Skip / pause / replay UX",
/// the dispatcher consults the seen-set + skip-confirm window before
/// allowing the skip to fire.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerSkipCinematicParams {
    #[serde(default)]
    pub schema_version: u32,
}

/// frozen; voice-over paused at boundary; subtitle frozen. Resume with
/// `[P]` again." Idempotent: the dispatcher inspects the current
/// phase to decide whether to fire `cinematic.paused` or
/// `cinematic.resumed`.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerPauseCinematicParams {
    #[serde(default)]
    pub schema_version: u32,
}

/// cinematic from `Codex → Cinematics`. Per spec § "Replay — any
/// cinematic the player has watched is unlocked / Replay runs the
/// script identically (replay-deterministic) without affecting save
/// state."
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerReplayCinematicParams {
    #[serde(default)]
    pub schema_version: u32,
    pub id: String,
}

/// `CinematicState` JSON view (cinematic id + source + phase +
/// playhead + duration + color grade + active word + camera offset).
/// Used by the Codex tab + cinematic editor + tests.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct SrvDumpCinematicStateParams {
    #[serde(default)]
    pub schema_version: u32,
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct RunBundleWriteParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub id_override: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct SystemShutdownParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub write_run_bundle: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerTreatParams {
    pub schema_version: u32,
    /// Canonical TreatmentKind id (PascalCase, e.g. "FieldBandageV1").
    pub kind: String,
    /// Target actor id (the patient).
    pub target_actor_id: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerScanParams {
    pub schema_version: u32,
    pub target_actor_id: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerCprRoundParams {
    pub schema_version: u32,
    pub target_actor_id: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerDefibParams {
    pub schema_version: u32,
    pub target_actor_id: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerSurgeryStartParams {
    pub schema_version: u32,
    pub target_actor_id: u64,
    /// Number of wounds to remove (drives the Operate-phase repeat count).
    pub wounds_to_treat: u32,
    /// True if the surgeon has surgeon_t1 (90% pass rate); false → medic_t1.
    pub surgeon_t1: bool,
    /// Optional seed override for deterministic skill-check rolls.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub seed: Option<u64>,
}

/// patient. `target_actor_id = None` clears the selection.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerTriageSelectParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub target_actor_id: Option<u64>,
}

/// a target actor. Requires medic_t2 + surgery table; runs the 60s install
/// sequence inline + emits `prosthetic.installed` on completion.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerInstallProstheticParams {
    pub schema_version: u32,
    pub target_actor_id: u64,
    /// Canonical ProstheticKind id (snake_case, e.g. "prosthetic_leg_t1").
    pub kind: String,
    /// Target zone (e.g. "leg_right"). Must be in the prosthetic's
    /// `target_zones` allow-list.
    pub zone: String,
}

/// on an installed prosthetic. Resets wear_pct to 0 + clears the
/// malfunction flag.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerMaintainProstheticParams {
    pub schema_version: u32,
    pub target_actor_id: u64,
    pub zone: String,
}

/// Only valid once `age.retirement_offered` has fired and the actor is at
/// least `retirement_age + 5`.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerRetireVeteranParams {
    pub schema_version: u32,
    pub target_actor_id: u64,
}

/// detect-driven. Enters Stance::Vault for `VAULT_DURATION_MS` ms and
/// emits `actor.vaulted`.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerVaultParams {
    pub schema_version: u32,
}

/// `WALL_CONTACT_GRACE_MS` of wall contact. Chain limit is 3 before
/// next ground contact.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerWallJumpParams {
    pub schema_version: u32,
}

/// grappling-hook gun at a world-space point. On hit the rope embeds + a
/// verlet rope spawns in cf-physics::rope.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerFireGrappleParams {
    pub schema_version: u32,
    pub target_x: f32,
    pub target_y: f32,
}

/// pull rope hand-over-hand or rappel + add tangential swing input at
/// the bob.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerRopeInputParams {
    pub schema_version: u32,
    /// -1.0 (rappel away) to +1.0 (climb toward anchor).
    pub climb: f32,
    /// -1.0 to +1.0 — tangential swing input at the bob.
    #[serde(default)]
    pub swing: f32,
}

/// rope; actor inherits the pendulum velocity at the instant of release.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerReleaseRopeParams {
    pub schema_version: u32,
}

/// deployed zip line at its high end.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerZiplineClipParams {
    pub schema_version: u32,
    pub line_id: u64,
}

/// release the zip-line brake.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerZiplineBrakeParams {
    pub schema_version: u32,
    pub engaged: bool,
}

/// critter. Enters Stance::Mounted; combined mass is rider + critter.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerMountParams {
    pub schema_version: u32,
    pub critter_id: u64,
}

/// when stationary; 200ms stagger + 70% velocity inherit when mid-motion.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerDismountParams {
    pub schema_version: u32,
}

/// Dump every M0 schema as `(filename, json-string)` pairs.
///
/// `cargo run -p cf-control --example dump_schemas` regenerates the static
/// files under `crates/cf-control/schemas/v1/`.
pub fn dump_v1() -> BTreeMap<String, String> {
    use crate::envelope::{JsonRpcError, JsonRpcId, JsonRpcNotification, JsonRpcRequest, JsonRpcResponse};
    use crate::server::SettingsPatch;
    use crate::settings::Settings;
    use crate::state::{ObserveFrame, ObserveSettings};

    fn entry<T: JsonSchema>(name: &str) -> (String, String) {
        let schema = schema_for!(T);
        (
            format!("{name}.schema.json"),
            serde_json::to_string_pretty(&schema).expect("schema serializes"),
        )
    }

    let mut out = BTreeMap::new();
    for (name, body) in [
        entry::<JsonRpcId>("json_rpc_id"),
        entry::<JsonRpcRequest>("json_rpc_request"),
        entry::<JsonRpcResponse>("json_rpc_response"),
        entry::<JsonRpcNotification>("json_rpc_notification"),
        entry::<JsonRpcError>("json_rpc_error"),
        entry::<ScenarioLoadParams>("scenario_load_params"),
        entry::<CommandAck>("command_ack"),
        entry::<StepParams>("step_params"),
        entry::<RunForTicksParams>("run_for_ticks_params"),
        entry::<ObserveOnceParams>("observe_once_params"),
        entry::<ObserveSubscribeParams>("observe_subscribe_params"),
        entry::<ActPlayerMoveParams>("act_player_move_params"),
        entry::<ActPlayerJumpParams>("act_player_jump_params"),
        entry::<ActPlayerAimParams>("act_player_aim_params"),
        entry::<ActPlayerFireParams>("act_player_fire_params"),
        entry::<ActPlayerReloadParams>("act_player_reload_params"),
        entry::<ActPlayerSelectItemParams>("act_player_select_item_params"),
        entry::<ActPlayerResetParams>("act_player_reset_params"),
        entry::<ActPlayerDigParams>("act_player_dig_params"),
        entry::<ActPlayerAnchorParams>("act_player_anchor_params"),
        entry::<ActPlayerDigTrenchSegmentParams>("act_player_dig_trench_segment_params"),
        entry::<ActPlayerPlaceTrenchModuleParams>("act_player_place_trench_module_params"),
        entry::<ActPlayerRepairTrenchModuleParams>("act_player_repair_trench_module_params"),
        entry::<ActPlayerDropTrenchTemplateParams>("act_player_drop_trench_template_params"),
        entry::<ObserveActorCoverStateParams>("observe_actor_cover_state_params"),
        entry::<ObserveTrenchSegmentAtPosParams>("observe_trench_segment_at_pos_params"),
        entry::<ObserveMissionParams>("observe_mission_params"),
        entry::<ObserveAiParams>("observe_ai_params"),
        entry::<ObservePerceptionParams>("observe_perception_params"),
        entry::<InspectMissionParams>("inspect_mission_params"),
        entry::<InspectAiParams>("inspect_ai_params"),
        entry::<ActPlayerCrouchParams>("act_player_crouch_params"),
        entry::<ActPlayerClimbParams>("act_player_climb_params"),
        entry::<ActPlayerJetParams>("act_player_jet_params"),
        entry::<ActPlayerEjectParams>("act_player_eject_params"),
        entry::<ActPlayerQuickActionSlotParams>("act_player_quick_action_slot_params"),
        entry::<ActPlayerQuickActionToggleParams>("act_player_quick_action_toggle_params"),
        entry::<ActPlayerQuickActionRadialParams>("act_player_quick_action_radial_params"),
        entry::<ActPlayerQuickActionSliceParams>("act_player_quick_action_slice_params"),
        entry::<ActPlayerWeaponCycleParams>("act_player_weapon_cycle_params"),
        entry::<ActChassisRepairParams>("act_chassis_repair_params"),
        entry::<ActChassisSalvageParams>("act_chassis_salvage_params"),
        entry::<ActChassisClearJamParams>("act_chassis_clear_jam_params"),
        entry::<ActPlayerSharpAimParams>("act_player_sharp_aim_params"),
        entry::<InspectEquipmentParams>("inspect_equipment_params"),
        entry::<ObserveActorParams>("observe_actor_params"),
        entry::<InspectActorParams>("inspect_actor_params"),
        entry::<InspectChassisParams>("inspect_chassis_params"),
        entry::<ActPlayerBrainHopParams>("act_player_brain_hop_params"),
        entry::<ActPlayerActivateAbilityParams>("act_player_activate_ability_params"),
        entry::<ActInputCameraAnchorParams>("act_input_camera_anchor_params"),
        entry::<ActPlayerSetDroneModeParams>("act_player_set_drone_mode_params"),
        entry::<ActPlayerAttachModifierParams>("act_player_attach_modifier_params"),
        entry::<ActPlayerDetachModifierParams>("act_player_detach_modifier_params"),
        entry::<ActPlayerBoardParams>("act_player_board_params"),
        entry::<ActPlayerDisembarkParams>("act_player_disembark_params"),
        entry::<ObserveChassisSilhouetteParams>("observe_chassis_silhouette_params"),
        entry::<ActPlayerAbortParams>("act_player_abort_params"),
        entry::<ActMissionPauseParams>("act_mission_pause_params"),
        entry::<ActMissionResumeParams>("act_mission_resume_params"),
        entry::<ActInputCaptureControlsParams>("act_input_capture_controls_params"),
        entry::<ActToggleMaterialOverlayParams>("act_toggle_material_overlay_params"),
        entry::<InspectTerrainChunkParams>("inspect_terrain_chunk_params"),
        entry::<InspectMaterialParams>("inspect_material_params"),
        entry::<ObserveTerrainMaterialAtParams>("observe_terrain_material_at_params"),
        entry::<RunBundleWriteParams>("run_bundle_write_params"),
        entry::<SystemShutdownParams>("system_shutdown_params"),
        entry::<SettingsPatch>("settings_patch"),
        entry::<Settings>("settings"),
        entry::<ObserveFrame>("observe_frame"),
        entry::<ObserveSettings>("observe_settings"),
        entry::<crate::state::ActorView>("actor_view"),
        entry::<ActSquadIssueParams>("act_squad_issue_params"),
        entry::<ActSquadSetFormationParams>("act_squad_set_formation_params"),
        entry::<ActSquadAssignRoleParams>("act_squad_assign_role_params"),
        entry::<SrvDumpSquadStateParams>("srv_dump_squad_state_params"),
        entry::<crate::m8b_net_admin::ObserveNetSessionTransportParams>("observe_net_session_transport_params"),
        entry::<crate::m8b_net_admin::ObserveNetRollbackStatsParams>("observe_net_rollback_stats_params"),
        entry::<crate::m8b_net_admin::ObserveNetLossRecoveryParams>("observe_net_loss_recovery_params"),
        entry::<crate::m8b_net_admin::AdminNetForceRelayParams>("admin_net_force_relay_params"),
        entry::<ActPlayerSkipCinematicParams>("act_player_skip_cinematic_params"),
        entry::<ActPlayerPauseCinematicParams>("act_player_pause_cinematic_params"),
        entry::<ActPlayerReplayCinematicParams>("act_player_replay_cinematic_params"),
        entry::<SrvDumpCinematicStateParams>("srv_dump_cinematic_state_params"),
        entry::<ActPlayerTreatParams>("act_player_treat_params"),
        entry::<ActPlayerScanParams>("act_player_scan_params"),
        entry::<ActPlayerCprRoundParams>("act_player_cpr_round_params"),
        entry::<ActPlayerDefibParams>("act_player_defib_params"),
        entry::<ActPlayerSurgeryStartParams>("act_player_surgery_start_params"),
        entry::<ActPlayerTriageSelectParams>("act_player_triage_select_params"),
        entry::<ActPlayerInstallProstheticParams>("act_player_install_prosthetic_params"),
        entry::<ActPlayerMaintainProstheticParams>("act_player_maintain_prosthetic_params"),
        entry::<ActPlayerRetireVeteranParams>("act_player_retire_veteran_params"),
        // gun / rope / zip line / mount cfctl surface.
        entry::<ActPlayerVaultParams>("act_player_vault_params"),
        entry::<ActPlayerWallJumpParams>("act_player_wall_jump_params"),
        entry::<ActPlayerFireGrappleParams>("act_player_fire_grapple_params"),
        entry::<ActPlayerRopeInputParams>("act_player_rope_input_params"),
        entry::<ActPlayerReleaseRopeParams>("act_player_release_rope_params"),
        entry::<ActPlayerZiplineClipParams>("act_player_zipline_clip_params"),
        entry::<ActPlayerZiplineBrakeParams>("act_player_zipline_brake_params"),
        entry::<ActPlayerMountParams>("act_player_mount_params"),
        entry::<ActPlayerDismountParams>("act_player_dismount_params"),
    ] {
        out.insert(name, body);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn scenario_load_schema_compiles() {
        let _schema = schema_for!(ScenarioLoadParams);
    }

    #[test]
    fn command_ack_schema_compiles() {
        let _schema = schema_for!(CommandAck);
    }

    #[test]
    fn dump_v1_includes_every_m0_method() {
        let schemas = dump_v1();
        for needed in [
            "json_rpc_request.schema.json",
            "json_rpc_response.schema.json",
            "json_rpc_notification.schema.json",
            "scenario_load_params.schema.json",
            "step_params.schema.json",
            "run_for_ticks_params.schema.json",
            "observe_once_params.schema.json",
            "observe_subscribe_params.schema.json",
            "act_player_move_params.schema.json",
            "run_bundle_write_params.schema.json",
            "system_shutdown_params.schema.json",
            "settings_patch.schema.json",
            "settings.schema.json",
            "observe_frame.schema.json",
            "observe_settings.schema.json",
            "command_ack.schema.json",
        ] {
            assert!(schemas.contains_key(needed), "missing {needed}");
        }
    }

    #[test]
    fn static_schema_files_match_dump() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("schemas/v1");
        if !dir.exists() {
            // CI / first-time run: the dump_schemas example writes them; the test acts as a guard.
            panic!(
                "static schemas missing under {}; run `cargo run -p cf-control --example dump_schemas` to regenerate",
                dir.display()
            );
        }
        let dumped = dump_v1();
        for (name, body) in &dumped {
            let path = dir.join(name);
            let on_disk =
                std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("read {} failed: {err}", path.display()));
            // Normalize trailing newlines from editors.
            assert_eq!(
                normalize(&on_disk),
                normalize(body),
                "static schema {} drifted from schemars derive; rerun `cargo run -p cf-control --example dump_schemas`",
                path.display()
            );
        }
    }

    fn normalize(s: &str) -> String {
        s.trim_end_matches('\n').to_string()
    }
}
