//! Schemas for the cf-control envelope. Output JSON Schema files live under
//! `crates/cf-control/schemas/v1/` and are regenerated by `cargo run -p cf-control --example
//! dump_schemas`. The crate test verifies the static files match the `schemars` output for
//! the current types.

use std::collections::BTreeMap;

use schemars::{schema_for, JsonSchema};
use serde::{Deserialize, Serialize};

/// Protocol schema version. Bumped from 1→2 at BP3 when M5 added
/// `act.player.crouch/climb/jet/eject` plus `act.chassis.repair/salvage/clear_jam`
/// plus `act.input.focus`. Clients sending `schema_version: 1` still work because
/// all new methods are additive (no field renames or type changes on v1 methods).
/// The dispatcher rejects `schema_version > SCHEMA_VERSION` with `-32602`.
pub const SCHEMA_VERSION: u32 = 2;

/// Minimum schema version accepted. v1 clients are still compatible because
/// no v1 method shapes changed — only new methods were added.
pub const SCHEMA_VERSION_MIN: u32 = 1;

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ScenarioLoadParams {
    pub schema_version: u32,
    pub scenario: String,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub seed: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct CommandAck {
    pub schema_version: u32,
    pub status: String,
    pub effective_tick: u64,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub reason: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct StepParams {
    pub schema_version: u32,
    pub ticks: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct RunForTicksParams {
    pub schema_version: u32,
    pub ticks: u64,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub write_run_bundle: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveOnceParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub filter: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveSubscribeParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub hz: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub filter: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerMoveParams {
    pub schema_version: u32,
    /// Move axis in [-1.0, +1.0]. Negative = left, positive = right.
    pub x: f32,
    /// Reserved for vertical input (ladders / climbing). Ignored in M1.
    #[serde(default)]
    pub y: f32,
}

/// `act.player.jump` — edge-triggered jump request.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerJumpParams {
    pub schema_version: u32,
}

/// `act.player.aim` — set the player's aim vector (will be normalized).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerAimParams {
    pub schema_version: u32,
    pub x: f32,
    pub y: f32,
}

/// `act.player.fire` — edge-triggered fire request.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerFireParams {
    pub schema_version: u32,
    /// `true` (default) = press fire this tick; `false` = explicit release for future
    /// hold-to-fire weapons. M1's rifle is single-press; release is a no-op.
    #[serde(default = "default_true")]
    pub pressed: bool,
}

/// `act.player.reload` — edge-triggered reload request.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerReloadParams {
    pub schema_version: u32,
}

/// `act.player.select_item` — set the active inventory slot.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerSelectItemParams {
    pub schema_version: u32,
    pub slot: u32,
}

/// `act.player.reset` — return the player to their spawn with full HP / ammo.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerResetParams {
    pub schema_version: u32,
}

/// `act.player.dig` — M1.5 soft-breach dig request. `target` picks an explicit
/// breach id; `None` means dig the nearest in-range strip.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerDigParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub target: Option<String>,
}

/// **M5**: `act.player.crouch` — sticky crouch toggle.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerCrouchParams {
    pub schema_version: u32,
    pub active: bool,
}

/// **M5**: `act.player.climb` — sticky climb toggle (placeholder cue).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerClimbParams {
    pub schema_version: u32,
    pub active: bool,
}

/// **M5**: `act.player.jet` — jet thrust toggle.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerJetParams {
    pub schema_version: u32,
    pub active: bool,
}

/// **M5**: `act.player.eject` — trigger pilot eject from a chassis.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerEjectParams {
    pub schema_version: u32,
}

/// **M5**: `act.chassis.repair` — repair a chassis zone or specific module.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActChassisRepairParams {
    pub schema_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub zone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub module_id: Option<String>,
    #[serde(default = "default_repair_reason")]
    pub reason: String,
}

fn default_repair_reason() -> String {
    "field_kit".to_string()
}

/// **M5**: `act.chassis.salvage` — salvage modules from a wrecked chassis.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActChassisSalvageParams {
    pub schema_version: u32,
    #[serde(default = "default_salvage_reason")]
    pub reason: String,
}

fn default_salvage_reason() -> String {
    "manual".to_string()
}

/// **M5**: `act.chassis.clear_jam` — manually clear a weapon jam.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActChassisClearJamParams {
    pub schema_version: u32,
}

/// **M1**: `act.player.sharp_aim` — sticky toggle for the sharp-aim hold
/// (CCCP `AHuman.cpp:1779`). While `active=true` the sim builds
/// `ActorState::sharp_aim_progress` toward 1.0 each tick as long as the
/// actor is STABLE, grounded, slow, and equipped; invalidations snap it back
/// to zero.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerSharpAimParams {
    pub schema_version: u32,
    pub active: bool,
}

/// **M1**: `inspect.equipment` — return the full `RifleSpec` (firing profile +
/// AI hints + tracer/particle metadata) for a preset id.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct InspectEquipmentParams {
    pub schema_version: u32,
    pub preset_id: String,
}

/// **M1**: `observe.actor` — return full `ActorView` (with M1 fields) for the
/// player by default, or for `actor_id` when supplied.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ObserveActorParams {
    pub schema_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<u64>,
}

/// **M1**: `inspect.actor` — return the full `ActorView` plus the last 30
/// `actor` events for the target. `target` is `"player"` for the controllable
/// actor or an actor id rendered as a string. Empty target defaults to player.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct InspectActorParams {
    pub schema_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
}

/// **M1 / Gap S3 (M1.5 forward-compat seam)**: `act.player.abort` —
/// stub at M1; flips to a real mission abort path at M1.5.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActPlayerAbortParams {
    pub schema_version: u32,
}

/// **M1.5**: `act.mission.pause` — suspend mission objective progress +
/// timer accounting (tutorial-modal pause path). Idempotent: invoking
/// twice in a row only emits one `mission.objective_paused` event.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActMissionPauseParams {
    #[serde(default)]
    pub schema_version: u32,
}

/// **M1.5**: `act.mission.resume` — lift the pause set by `act.mission.pause`.
/// Idempotent: only emits `mission.objective_resumed` when actually paused.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActMissionResumeParams {
    #[serde(default)]
    pub schema_version: u32,
}

/// **M1 / Gap D1**: `act.input.capture_controls` — UI signals the engine
/// that an overlay (settings panel, debrief prompt, future pause/menu) has
/// captured input. `captured=true` raises the CONTROLS CAPTURED HUD badge
/// and rejects subsequent `act.player.*` dispatches; `captured=false`
/// releases. `capturer` carries a short human-readable label.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ActInputCaptureControlsParams {
    pub schema_version: u32,
    pub captured: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capturer: Option<String>,
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct RunBundleWriteParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub id_override: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct SystemShutdownParams {
    pub schema_version: u32,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub write_run_bundle: Option<bool>,
}

/// Dump every M0 schema as `(filename, json-string)` pairs.
///
/// `cargo run -p cf-control --example dump_schemas` regenerates the static
/// files under `crates/cf-control/schemas/v1/`.
pub fn dump_v1() -> BTreeMap<String, String> {
    use crate::envelope::{JsonRpcError, JsonRpcId, JsonRpcNotification, JsonRpcRequest, JsonRpcResponse};
    use crate::server::SettingsPatch;
    use crate::settings::Settings;
    use crate::state::{ObserveFrame, ObserveSettings};

    fn entry<T: JsonSchema>(name: &str) -> (String, String) {
        let schema = schema_for!(T);
        (
            format!("{name}.schema.json"),
            serde_json::to_string_pretty(&schema).expect("schema serializes"),
        )
    }

    let mut out = BTreeMap::new();
    for (name, body) in [
        entry::<JsonRpcId>("json_rpc_id"),
        entry::<JsonRpcRequest>("json_rpc_request"),
        entry::<JsonRpcResponse>("json_rpc_response"),
        entry::<JsonRpcNotification>("json_rpc_notification"),
        entry::<JsonRpcError>("json_rpc_error"),
        entry::<ScenarioLoadParams>("scenario_load_params"),
        entry::<CommandAck>("command_ack"),
        entry::<StepParams>("step_params"),
        entry::<RunForTicksParams>("run_for_ticks_params"),
        entry::<ObserveOnceParams>("observe_once_params"),
        entry::<ObserveSubscribeParams>("observe_subscribe_params"),
        entry::<ActPlayerMoveParams>("act_player_move_params"),
        entry::<ActPlayerJumpParams>("act_player_jump_params"),
        entry::<ActPlayerAimParams>("act_player_aim_params"),
        entry::<ActPlayerFireParams>("act_player_fire_params"),
        entry::<ActPlayerReloadParams>("act_player_reload_params"),
        entry::<ActPlayerSelectItemParams>("act_player_select_item_params"),
        entry::<ActPlayerResetParams>("act_player_reset_params"),
        entry::<ActPlayerDigParams>("act_player_dig_params"),
        entry::<ActPlayerCrouchParams>("act_player_crouch_params"),
        entry::<ActPlayerClimbParams>("act_player_climb_params"),
        entry::<ActPlayerJetParams>("act_player_jet_params"),
        entry::<ActPlayerEjectParams>("act_player_eject_params"),
        entry::<ActChassisRepairParams>("act_chassis_repair_params"),
        entry::<ActChassisSalvageParams>("act_chassis_salvage_params"),
        entry::<ActChassisClearJamParams>("act_chassis_clear_jam_params"),
        entry::<ActPlayerSharpAimParams>("act_player_sharp_aim_params"),
        entry::<InspectEquipmentParams>("inspect_equipment_params"),
        entry::<ObserveActorParams>("observe_actor_params"),
        entry::<InspectActorParams>("inspect_actor_params"),
        entry::<ActPlayerAbortParams>("act_player_abort_params"),
        entry::<ActMissionPauseParams>("act_mission_pause_params"),
        entry::<ActMissionResumeParams>("act_mission_resume_params"),
        entry::<ActInputCaptureControlsParams>("act_input_capture_controls_params"),
        entry::<RunBundleWriteParams>("run_bundle_write_params"),
        entry::<SystemShutdownParams>("system_shutdown_params"),
        entry::<SettingsPatch>("settings_patch"),
        entry::<Settings>("settings"),
        entry::<ObserveFrame>("observe_frame"),
        entry::<ObserveSettings>("observe_settings"),
        entry::<crate::state::ActorView>("actor_view"),
    ] {
        out.insert(name, body);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn scenario_load_schema_compiles() {
        let _schema = schema_for!(ScenarioLoadParams);
    }

    #[test]
    fn command_ack_schema_compiles() {
        let _schema = schema_for!(CommandAck);
    }

    #[test]
    fn dump_v1_includes_every_m0_method() {
        let schemas = dump_v1();
        for needed in [
            "json_rpc_request.schema.json",
            "json_rpc_response.schema.json",
            "json_rpc_notification.schema.json",
            "scenario_load_params.schema.json",
            "step_params.schema.json",
            "run_for_ticks_params.schema.json",
            "observe_once_params.schema.json",
            "observe_subscribe_params.schema.json",
            "act_player_move_params.schema.json",
            "run_bundle_write_params.schema.json",
            "system_shutdown_params.schema.json",
            "settings_patch.schema.json",
            "settings.schema.json",
            "observe_frame.schema.json",
            "observe_settings.schema.json",
            "command_ack.schema.json",
        ] {
            assert!(schemas.contains_key(needed), "missing {needed}");
        }
    }

    #[test]
    fn static_schema_files_match_dump() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("schemas/v1");
        if !dir.exists() {
            // CI / first-time run: the dump_schemas example writes them; the test acts as a guard.
            panic!(
                "static schemas missing under {}; run `cargo run -p cf-control --example dump_schemas` to regenerate",
                dir.display()
            );
        }
        let dumped = dump_v1();
        for (name, body) in &dumped {
            let path = dir.join(name);
            let on_disk =
                std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("read {} failed: {err}", path.display()));
            // Normalize trailing newlines from editors.
            assert_eq!(
                normalize(&on_disk),
                normalize(body),
                "static schema {} drifted from schemars derive; rerun `cargo run -p cf-control --example dump_schemas`",
                path.display()
            );
        }
    }

    fn normalize(s: &str) -> String {
        s.trim_end_matches('\n').to_string()
    }
}
