[package]
name = "cf-squad-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde = { workspace = true }
tracing = { workspace = true }
cf-priority = { path = "../cf-priority" }

[dev-dependencies]
serde_json = { workspace = true }
