[package]
name = "cf-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
bevy = { workspace = true }
cf-actor = { path = "../cf-actor" }
cf-ai = { path = "../cf-ai" }
cf-equipment = { path = "../cf-equipment" }
cf-terrain = { path = "../cf-terrain" }
