[package]
name = "cf-ai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde = { workspace = true }
tracing = { workspace = true }
cf-actor = { path = "../cf-actor" }
cf-sim-core = { path = "../cf-sim-core" }
