[package]
name = "cf-environment"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
cf-wound = { path = "../cf-wound" }

[dev-dependencies]
serde_json = { workspace = true }
